ROOT := justfile_directory()
ALEMBIC_CONFIG := ROOT / "pyproject.toml"
HOST := env("HOST", "0.0.0.0")
PORT := env("PORT", "8001")
WORKERS := env("WORKERS", "4")
APP := env("APP", "cmd.main:app")
TASKS_PATH := ROOT / "apps" / "tasks"
TASKS_MODULES := "apps.tasks"

default:
    just --list

make-migration MESSAGE:
    #! /bin/bash
    PYTHONPATH=. uv run alembic -c {{ ALEMBIC_CONFIG }} revision --autogenerate -m {{ MESSAGE }}

migrate REV="head":
    #! /bin/bash
    PYTHONPATH=. uv run alembic -c {{ ALEMBIC_CONFIG }} upgrade {{ REV }}

migrate-with-data REV="head":
    #! /bin/bash
    PYTHONPATH=. uv run python -m cmd.migrate_with_data {{ REV }}

downgrade REV="base":
    #! /bin/bash
    PYTHONPATH=. uv run alembic -c {{ ALEMBIC_CONFIG }} downgrade {{ REV }}

db-current:
    #! /bin/bash
    PYTHONPATH=. uv run alembic -c {{ ALEMBIC_CONFIG }} current

db-history:
    #! /bin/bash
    PYTHONPATH=. uv run alembic -c {{ ALEMBIC_CONFIG }} history

db-stamp REV="head":
    #! /bin/bash
    PYTHONPATH=. uv run alembic -c {{ ALEMBIC_CONFIG }} stamp {{ REV }}

lint:
    ruff check .

lint-fix:
    ruff check --fix .

format:
    ruff format .

check: lint format

run: dev

prod:
    gunicorn \
        -w "{{ WORKERS }}" \
        -k uvicorn.workers.UvicornWorker \
        --bind {{ HOST }}:{{ PORT }} \
        {{ APP }}

dev:
    uvicorn {{ APP }} \
        --host {{ HOST }} \
        --port {{ PORT }} \
        --reload

dramatiq:
    dramatiq {{ TASKS_MODULES }} \
        --watch {{ TASKS_PATH }} \
        --processes {{ WORKERS }}

taskiq:
    taskiq \
    worker \
    {{ TASKS_MODULES }}:broker \
    --log-level WARNING

asynctasq-worker QUEUES="default" CONCURRENCY="10":
    uv run asynctasq worker \
        --queues {{ QUEUES }} \
        --concurrency {{ CONCURRENCY }}

help:
    @just --list

sync:
    uv sync

run-prod:
    uv run uvicorn cmd.main:app --host 0.0.0.0 --port 8001

test:
    uv run pytest

docker-ps:
    docker ps

docker-compose-up:
    docker compose up -d --build

docker-compose-start:
    docker compose start

docker-compose-stop:
    docker compose stop

docker-compose-down:
    docker compose down

docker-compose-logs:
    docker compose logs -f
